# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.27
# 

Name:       harbour-contrac

# >> macros
# << macros

Summary:    Contrac
Version:    0.5.1
Release:    1
Group:      Qt/Qt
License:    LICENSE
URL:        https://www.flypig.co.uk/contrac
Source0:    %{name}-%{version}.tar.bz2
Source100:  harbour-contrac.yaml
Requires:   sailfishsilica-qt5 >= 0.10.9
Requires:   openssl
Requires:   protobuf-lite
Requires:   nemo-qml-plugin-time-qt5
BuildRequires:  pkgconfig(sailfishapp) >= 1.0.2
BuildRequires:  pkgconfig(Qt5Core)
BuildRequires:  pkgconfig(Qt5Qml)
BuildRequires:  pkgconfig(Qt5Quick)
BuildRequires:  pkgconfig(openssl)
BuildRequires:  pkgconfig(Qt5Test)
BuildRequires:  pkgconfig(protobuf-lite)
BuildRequires:  pkgconfig(libcurl)
BuildRequires:  pkgconfig(libxml-2.0)
BuildRequires:  pkgconfig(quazip)
BuildRequires:  protobuf-compiler
BuildRequires:  desktop-file-utils

%description
Short description of my Sailfish OS Application


%package tests
Summary:    Tests for harbour-contrac
Group:      Qt/Qt
Requires:   %{name} = %{version}-%{release}
Requires:   qt5-qtdeclarative-import-qttest
BuildRequires:  pkgconfig(Qt5QuickTest)

%description tests
Unit tests

%prep
%setup -q -n %{name}-%{version}

# >> setup
# << setup

%build
# >> build pre
# << build pre

%qmake5 

make %{?_smp_mflags}

# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%qmake5_install

# >> install post
%post
if [ "$1" -ge 1 ]; then
systemctl-user daemon-reload || true
systemctl-user restart contracd.service || true
systemctl-user enable contracd.service || true
fi

%postun
if [ "$1" -eq 0 ]; then
systemctl-user stop contracd.service || true
systemctl-user disable contracd.service || true
systemctl-user daemon-reload || true
fi
# << install post

desktop-file-install --delete-original       \
  --dir %{buildroot}%{_datadir}/applications             \
   %{buildroot}%{_datadir}/applications/*.desktop

%files
%defattr(-,root,root,-)
%{_bindir}
%{_datadir}/%{name}
%{_datadir}/applications/%{name}.desktop
%{_datadir}/icons/hicolor/*/apps/%{name}.png
%{_datadir}/%{name}/translations
%{_bindir}/contracd
%{_libdir}/systemd/user/contracd.service
%{_datadir}/mapplauncherd/privileges.d/contracd.privileges
# >> files
# << files

%files tests
%defattr(-,root,root,-)
%{_libdir}/%{name}-tests/%{name}-tests
%{_datadir}/%{name}-tests/sample_diagnosis_key_file.zip
# >> files tests
# << files tests
